[meta title:"Calculus Notes" description:"Notes from Math 1B" /]

[Header
  title:"CS Notes"
  subtitle:"I hope this works"
  author:"Andres Duarte"
  authorLink:"https://idyll-lang.github.io" /]

I'm not sure if this is the right approach, but at this stage I don't think I have an alternative. 
